apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-namespace: "default"
  labels:
  name: kube-server
  namespace: default
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["deployments"]
  verbs:
  - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-server-binding
  annotations:
      app.kubernetes.io/managed-by: "Helm"
      meta.helm.sh/release-namespace: "default"
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-server
roleRef:
  kind: ClusterRole
  name: kube-server
  apiGroup: rbac.authorization.k8s.io