apiVersion: v1
kind: Service
metadata:
  name: kube-server-svc
  namespace: kube-server
  annotations:
    app.kubernetes.io/managed-by: "Helm"
    meta.helm.sh/release-namespace: "default"
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}
    nodePort: {{ .Values.service.nodePort }}
    protocol: TCP
    name: http
  selector:
    app: kube-server
