apiVersion: v1
kind: Namespace
metadata:
  name: kube-server-dev

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
  name: kube-server-dev
  namespace: default
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources: ["deployments"]
  verbs:
  - patch
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-server-dev-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: kube-server-dev
roleRef:
  kind: ClusterRole
  name: kube-server-dev
  apiGroup: rbac.authorization.k8s.io