# Default values for kube-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: kube-server
  # We need this for Minikube since we are pulling the image locally
  # This should be Always once we start releasing and publishing the image on Dockerhub
  pullPolicy: Never
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

container:  
  containerPort: 8443
  userID: 1000
  groupID: 1000

service:
  nodePort: 30443
  port: 8443

redis:
  redisAddr: "redis-master.redis.svc.cluster.local:6379"