name: Docker Publish CI

on:
  push:
    branches:
      - "main"
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  go-build-linux:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-go@v3
       with:
          go-version: '>=1.18.0'
          cache: true
     - name: Set env for Version
       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
     - run: echo "Attempting to build a linux binary"
     - run: GOOS=linux GOARCH=amd64 go build -ldflags="main.Version='${{ env.RELEASE_VERSION }}'" -o ./kube-server-linux ./cmd/kube-server/main.go
     - run: echo "Outputting Version"
     - run: ./kube-server-linux --version
     - uses: actions/upload-artifact@v2
       with:
         name: kube-server-linux
         path: ./kube-server-linux
  docker-publish:
    needs: go-build-linux
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            taylorsmcclure/kube-server
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Download the golang binary
        uses: actions/download-artifact@v2
        with:
          name: kube-server-linux
          path: cmd/kube-server/bin/kube-server-linux
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}