name: Go Tests
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
          cache: true
      - run: go version
      - run: echo "Checking if gofmt finds anything"
      - run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
      - run: echo "Running unit tests"
      - run: go test -v ./...
  staticcheck:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running staticcheck"
      - uses: actions/checkout@v3
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
  build-linux:
    needs: [unit-tests, staticcheck]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-go@v3
       with:
          go-version: '>=1.18.0'
          cache: true
     - run: echo "Attempting to build a linux binary"
     # TODO: I read about ldflags and setting the Version var in my main.go
     - run: GOOS=linux GOARCH=amd64 go build -o ./kube-server-linux ./cmd/kube-server/main.go
     - run: echo "Outputting Version"
     - run: ./kube-server-linux --version
     - uses: actions/upload-artifact@v2
       with:
         name: kube-server-linux
         path: artifacts/kube-server-linux